config/routes.rb
Blogcms::Application.routes.draw do
  resources :articles

  root to:"articles#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :name

  validates :name, :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <script type="text/javascript">
      tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        language: "pl",
        plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : "css/example.css",

        // Drop lists for link/image/media/template dialogs
        template_external_list_url : "js/template_list.js",
        external_link_list_url : "js/link_list.js",
        external_image_list_url : "js/image_list.js",
        media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
      }
    });
    </script>
    <%= f.text_area :content, :class => "tinymce" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html-kopia.erb
<div id="middle" align="center" >

	<table>
  		<tr>
    		<th></th>
    		<th></th>
    		<th></th>
    		<th></th>
    		<th></th>
  		</tr>
  
	<% @articles.reverse_each do |article| %>
      
      <tr>
        
    		<td><center>
          <%= image_tag("papyrus1.png") %>
          <div id="artykul" align="center" style="background-image: url(/assets/papyrus2.png);"><h1><%= article.name %></h1><%= raw article.content %>
          </div>
          <%= image_tag("papyrus3.png") %>

        </td>
        
    		<td></td>
  		</tr>
  		<tr>
    		<td><center><%= link_to 'Show', article %> <%= link_to 'Edit', edit_article_path(article) %> <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
    		<td><center></center></td>
    		<td><center></center></td>
  		</tr>
      <tr>

        <center><td>--------------------------------------------------------------------------------------------------</td></center>
        
      </tr>

	<% end %>
  
	</table>
	<br />

	<%= link_to 'New Article', new_article_path %>
  

</div>

</center>

app/views/articles/index.html.erb
<div id="content">
  <section id="news">
    <article id="">
      <% @articles.reverse_each do |article| %>  
        <ul id="artykuly" class="box">
          <li><header id="tytul" class="artykuly-post"><h1><%= link_to article.name, article %></h1></header></li>
          <li><p id="tresc"><%= raw truncate(article.content, :length => 1500, :separator => ' ') %></p></li>
        </ul>
        <center><%= link_to 'Show', article %> <%= link_to 'Edit', edit_article_path(article) %> <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></center>
      <% end %>
    </article>
  
    <center><%= link_to 'New Article', new_article_path %></center>
  </section>
</div>

app/views/articles/index3.html.erb
<center>
<h1>Lista Artykulow</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><center><%= article.name %></center><br /><center><%= raw article.content %></center></td>
    <td></td>
  </tr>
  <tr>
    <td><center><%= link_to 'Show', article %> <%= link_to 'Edit', edit_article_path(article) %> <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
    <td><center></center></td>
    <td><center></center></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>
</center>

app/views/articles/new.html.erb
<center>
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</center>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div id="content">
  <section id="">
    <article id="">
        <ul id="artykuly">
          <li><header id="tytul"><h1><%= @article.name %></h1></header></li>
          <li><p id="tresc"><%= raw @article.content %></p></li>
        </ul>
        <center><%= link_to 'Edit', edit_article_path(@article) %> | <%= link_to 'Back', articles_path %></center>
    
    </article>
  
    
  </section>
</div>
 

app/views/layouts/application-kopia.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>
  <% if defined? @article.name %>
    Porque: <%= @article.name %>
  <% else %>
    <%= "Blog Porque" %>
  <% end %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= tinymce_assets %>
  <%= csrf_meta_tags %>
</head>
<body style="background-image: url(/assets/drewno.jpg);">

<p style="color: green"><%= flash[:notice] %></p>

<div id="container" align="center">
	<div id="logo">
    <%= link_to image_tag("blogheader.jpg"), root_path %>
	</div>

  <div id="menu">
    <h1>Test Menu</h1>
  </div>

  <div id="left">
    <h1>Test Menu Lewe</h1>
  </div>

	<%= yield %>

  <div id="right">
    <h1>Test Menu Prawe</h1>
  </div>

  <center><div id="footer" align="center">
    <br>
    <%= link_to 'Blog created by Porque!', root_path %>
  </div>

</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
<head>
<meta charset="utf-8" />
  <title>
  <% if defined? @article.name %>
    Porque: <%= @article.name %>
  <% else %>
    <%= "Blog Porque" %>
  <% end %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= tinymce_assets %>
  <%= csrf_meta_tags %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>
<header>
    <a href="<%= root_path %>" id="logo"><h1 class="texthide">Border &amp; Radius Brewhouse</h1></a>
</header> 

<nav id="primary">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'O mnie', root_path %></li>
        <li><%= link_to 'Kontakt', root_path %></li>
        <li><%= link_to 'Nowy artykul', new_article_path %></li>
      </ul>
</nav>

<div id="wrap">

	<%= yield %>


    <footer id="primary-foot">
    <section id="history">
      <header><h1>Co uzyte?</h1></header>
      <p>Do tego projektu w ramach nauki zostal uzyty: ror, html5 i css3.<br /> 
      
    </section>
    
    <section id="info">
      <nav id="footer-nav">
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">O mnie</a></li>
          <li><a href="#">Kontakt</a></li>
        </ul>
      </nav>
      
      <p class="copyright">&copy; 2013 wykop.pl/ludzie/porque/, Blog CMS by Porque<br />
      Pierwsza odslona, psuedo systemu cms do bloga.</p>
    </section>
  
  </footer>

</div>

</body>
</html>